version: '3'

services:
  nginx:
    container_name: project-nginx
    build: docker/nginx
    working_dir: /var/www/app
    ports:
      - "9969:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default-compose.conf:/etc/nginx/conf.d/default-compose.conf
    networks:
      - project-network

  php:
    container_name: project-fpm
    build: docker/php
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    networks:
      - project-network

  mysql:
    container_name: project-mysql
    build: docker/mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d/init.sql
    networks:
      - project-network

  phpmyadmin:
    container_name: project-phpmyadmin
    build: docker/phpmyadmin
    restart: on-failure
    ports:
      - "7999:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/phpmyadmin/upload.ini:/usr/local/etc/php/php.ini
    networks:
      - project-network

networks:
  project-network: